language: node_js
node_js:
  - "stable"
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - REACT_APP_HOSTNAME=sshort.me npm run build
before_deploy:
  pip install --user awscli
deploy:
  provider: script
  script: >-
    docker build -t aleksanderbrzozowski/rso-frontend . && 
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && 
    docker push aleksanderbrzozowski/rso-frontend && 
    ~/.local/bin/aws ecs update-service --cluster sshort-cluster --service frontend --region us-east-1 --force-new-deployment
  skip_cleanup: true
  on:
    branch: master
    condition: $DEPLOY = TRUE
